In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("Global_Terror.csv")

In [3]:
df.head(5)

,Unnamed: 0,Year,Month,Day,Country,Region,city,latitude,longitude,AttackType,Killed,Wounded,Target,Summary,Group,Target_type,Weapon_type,Motive
0,0,1970,7,2,Dominican Republic,Central America & Caribbean,Santo Domingo,18.456792,-69.951164,Assassination,1.0,0.0,Julio Guzman,NaN,MANO-D,Private Citizens & Property,Unknown,NaN
1,1,1970,0,0,Mexico,North America,Mexico city,19.432608,-99.133207,Hostage Taking (Kidnapping),0.0,0.0,"Nadine Chaval, daughter",NaN,23rd of September Communist League,Government (Diplomatic),Unknown,NaN
2,2,1970,1,0,Philippines,Southeast Asia,Unknown,15.478598,120.599741,Assassination,1.0,0.0,Employee,NaN,Unknown,Journalists & Media,Unknown,NaN
3,3,1970,1,0,Greece,Western Europe,Athens,37.983773,23.728157,Bombing/Explosion,NaN,NaN,U.S. Embassy,NaN,Unknown,Government (Diplomatic),Explosives/Bombs/Dynamite,NaN
4,4,1970,1,0,Japan,East Asia,Fukouka,33.580412,130.396361,Facility/Infrastructure Attack,NaN,NaN,U.S. Consulate,NaN,Unknown,Government (Diplomatic),Incendiary,NaN

In [4]:
df.tail(5)

,Unnamed: 0,Year,Month,Day,Country,Region,city,latitude,longitude,AttackType,Killed,Wounded,Target,Summary,Group,Target_type,Weapon_type,Motive
170345,170345,2016,12,31,Niger,Sub-Saharan Africa,Garoua,13.883032,13.177504,Unknown,15.0,7.0,Soldiers,12/31/2016: Assailants attacked military posit...,Boko Haram,Military,Unknown,NaN
170346,170346,2016,12,31,Philippines,Southeast Asia,Talitay,7.027067,124.386552,Bombing/Explosion,0.0,0.0,Convoy of Relief Workers,12/31/2016: An explosive device detonated targ...,Unknown,NGO,Explosives/Bombs/Dynamite,NaN
170347,170347,2016,12,31,Democratic Republic of the Congo,Sub-Saharan Africa,Nakolongbo,4.308611,25.091389,Hostage Taking (Kidnapping),0.0,NaN,Village,12/31/2016: Assailants attacked a village and ...,Lord's Resistance Army (LRA),Private Citizens & Property,Unknown,"The specific motive is unknown; however, sourc..."
170348,170348,2016,12,31,Mexico,North America,Guachochi,26.819644,-107.069898,Assassination,0.0,0.0,Residence of Journalist: Gabriel Valencia Juarez,12/31/2016: Assailants opened fire on the hous...,Unknown,Journalists & Media,Firearms,NaN
170349,170349,2016,12,30,Sudan,Sub-Saharan Africa,Nertiti,12.961401,24.044116,Armed Assault,0.0,0.0,Town,12/30/2016: Assailants armed with firearms att...,Sudan Liberation Movement,Private Citizens & Property,Firearms,NaN

In [5]:
df.dtypes

Unnamed: 0       int64
Year             int64
Month            int64
Day              int64
Country            str
Region             str
city               str
latitude       float64
longitude      float64
AttackType         str
Killed         float64
Wounded        float64
Target             str
Summary            str
Group              str
Target_type        str
Weapon_type        str
Motive             str
dtype: object

In [6]:
df.isnull().sum()

Unnamed: 0          0
Year                0
Month               0
Day                 0
Country             0
Region              0
city              447
latitude         4606
longitude        4606
AttackType          0
Killed           9682
Wounded         15325
Target            638
Summary         66138
Group               0
Target_type         0
Weapon_type         0
Motive         121764
dtype: int64

df['city'] = df.groupby('Country')['city'].transform(
    lambda x: x.fillna(x.mode()[0] if not x.mode().empty else 'Unknown')
)    #This will help to fiil null value with the country group by city so, whatever the city will be fill it will be in that matching country column

In [7]:
df['city'] = df['city'].fillna('Unknown') 
#replace a missing city with a guessed city, you're actually creating information that wasn't present in the original data.
#I'd keep the missing cities as NaN or label them "Unknown" rather than guessing them.

In [8]:
#Replace "Unknown" later when you discover the actual value
#df['city'] = df['city'].replace('Unknown', 'Delhi')

In [9]:
df['Target'] = df['Target'].fillna('Unknown')
df['Summary'] = df['Summary'].fillna('No summary available')
df['Motive'] = df['Motive'].fillna('Unknown')

In [10]:
df.isnull().sum()

Unnamed: 0         0
Year               0
Month              0
Day                0
Country            0
Region             0
city               0
latitude        4606
longitude       4606
AttackType         0
Killed          9682
Wounded        15325
Target             0
Summary            0
Group              0
Target_type        0
Weapon_type        0
Motive             0
dtype: int64

In [11]:
df[["Killed","Wounded"]].describe()

              Killed        Wounded
count  160668.000000  155025.000000
mean        2.387246       3.200239
std        11.327709      34.647365
min         0.000000       0.000000
25%         0.000000       0.000000
50%         0.000000       0.000000
75%         2.000000       2.000000
max      1500.000000    7366.000000

In [12]:
df[["Killed","Wounded"]].isnull().sum()

Killed      9682
Wounded    15325
dtype: int64

In [13]:
missing_percentage = df[["Killed","Wounded"]].isnull().mean() * 100

print(missing_percentage)

Killed     5.683593
Wounded    8.996184
dtype: float64

In [16]:
print("Killed = 0:", (df['Killed']==0).sum())
print("Wounded = 0:", (df['Wounded']==0).sum())

Killed = 0: 82925
Wounded = 0: 97182

In [17]:
# 3. Look at missing records
df[df['Killed'].isnull()][
    ['Year', 'Country', 'AttackType', 'Target', 'Killed', 'Wounded']
].head(20)

,Year,Country,AttackType,Target,Killed,Wounded
3,1970,Greece,Bombing/Explosion,U.S. Embassy,NaN,NaN
4,1970,Japan,Facility/Infrastructure Attack,U.S. Consulate,NaN,NaN
15,1970,East Germany (GDR),Bombing/Explosion,Jurists Ball (Palais au Frankturm),NaN,NaN
34,1970,East Germany (GDR),Facility/Infrastructure Attack,Residence of President of Penal Office,NaN,NaN
95,1970,Jordan,Armed Assault,Tourist Bus,NaN,NaN
176,1970,Argentina,Armed Assault,HQ. Patricios Infantry Regiment,NaN,NaN
241,1970,East Germany (GDR),Facility/Infrastructure Attack,Court Bldg,NaN,NaN
277,1970,Switzerland,Bombing/Explosion,Iberia Airlines Aircraft,NaN,NaN
288,1970,West Germany (FRG),Facility/Infrastructure Attack,"Savings and Loan of West Berlin, Branch #12",NaN,NaN
290,1970,West Germany (FRG),Armed Assault,Bank,NaN,NaN
324,1970,West Germany (FRG),Armed Assault,Xerox Building,NaN,NaN
325,1970,West Germany (FRG),Armed Assault,Court Building,NaN,NaN
329,1970,Jordan,Hostage Taking (Kidnapping),"Morris Draper, chief of political section, U.S...",NaN,0.0
334,1970,Iran,Bombing/Explosion,EL AL Office,NaN,NaN
335,1970,United States,Bombing/Explosion,police HQ,NaN,NaN
342,1970,Iran,Bombing/Explosion,EL AL Office,NaN,NaN
349,1970,West Germany (FRG),Facility/Infrastructure Attack,Court House/ Tiergarten,NaN,NaN
350,1970,West Germany (FRG),Facility/Infrastructure Attack,Court Bldg (haudgeright Tegeler Weg),NaN,NaN
355,1970,United States,Bombing/Explosion,bank america branch,NaN,NaN
360,1970,West Germany (FRG),Facility/Infrastructure Attack,District Office Schoneberg,NaN,NaN

In [18]:
df[df['Wounded'].isnull()][
    ['Year', 'Country', 'AttackType', 'Target', 'Killed', 'Wounded']
].head(20)

,Year,Country,AttackType,Target,Killed,Wounded
3,1970,Greece,Bombing/Explosion,U.S. Embassy,NaN,NaN
4,1970,Japan,Facility/Infrastructure Attack,U.S. Consulate,NaN,NaN
15,1970,East Germany (GDR),Bombing/Explosion,Jurists Ball (Palais au Frankturm),NaN,NaN
34,1970,East Germany (GDR),Facility/Infrastructure Attack,Residence of President of Penal Office,NaN,NaN
59,1970,West Germany (FRG),Armed Assault,El Al Passenger Bus & Airport Lounge,1.0,NaN
95,1970,Jordan,Armed Assault,Tourist Bus,NaN,NaN
171,1970,Ireland,Armed Assault,"Richard Fallon, 42, Garda Siochana",1.0,NaN
176,1970,Argentina,Armed Assault,HQ. Patricios Infantry Regiment,NaN,NaN
241,1970,East Germany (GDR),Facility/Infrastructure Attack,Court Bldg,NaN,NaN
277,1970,Switzerland,Bombing/Explosion,Iberia Airlines Aircraft,NaN,NaN
288,1970,West Germany (FRG),Facility/Infrastructure Attack,"Savings and Loan of West Berlin, Branch #12",NaN,NaN
290,1970,West Germany (FRG),Armed Assault,Bank,NaN,NaN
324,1970,West Germany (FRG),Armed Assault,Xerox Building,NaN,NaN
325,1970,West Germany (FRG),Armed Assault,Court Building,NaN,NaN
334,1970,Iran,Bombing/Explosion,EL AL Office,NaN,NaN
335,1970,United States,Bombing/Explosion,police HQ,NaN,NaN
342,1970,Iran,Bombing/Explosion,EL AL Office,NaN,NaN
349,1970,West Germany (FRG),Facility/Infrastructure Attack,Court House/ Tiergarten,NaN,NaN
350,1970,West Germany (FRG),Facility/Infrastructure Attack,Court Bldg (haudgeright Tegeler Weg),NaN,NaN
355,1970,United States,Bombing/Explosion,bank america branch,NaN,NaN

In [19]:
pd.crosstab(
    df['Killed'].isnull(),
    df['Wounded'].isnull()
)

Wounded   False  True
Killed
False    154524   6144
True        501   9181

In [21]:
(df['Killed'] == 0).sum()

np.int64(82925)

In [22]:
(df['Wounded'] == 0).sum()

np.int64(97182)

In [23]:
df.groupby('Year')['Killed'].apply(lambda x: x.isnull().sum()).sort_values(ascending=False).head(10)
#"Which years have the most missing Killed values?"

Year
2014    1014
1983     896
1982     802
2015     797
2016     781
1984     690
1981     658
1980     451
1985     440
1979     405
Name: Killed, dtype: int64

In [24]:
df.groupby('Country')['Killed'].apply(lambda x: x.isnull().sum()).sort_values(ascending=False).head(10)

Country
El Salvador    1381
Peru            638
Iraq            596
Somalia         580
Nicaragua       548
Colombia        456
Chile           413
Guatemala       328
Spain           293
Afghanistan     290
Name: Killed, dtype: int64

In [25]:
df.groupby('Country')['Wounded'].apply(lambda x: x.isnull().sum()).sort_values(ascending=False).head(10)

Country
United Kingdom    1714
El Salvador       1419
Iraq              1132
Nigeria            891
Somalia            836
Peru               703
Afghanistan        631
Nicaragua          626
Colombia           581
Syria              514
Name: Wounded, dtype: int64

In [26]:
df[['Killed', 'Wounded']].describe()

              Killed        Wounded
count  160668.000000  155025.000000
mean        2.387246       3.200239
std        11.327709      34.647365
min         0.000000       0.000000
25%         0.000000       0.000000
50%         0.000000       0.000000
75%         2.000000       2.000000
max      1500.000000    7366.000000

In [27]:
print("Killed = 0:", (df['Killed'] == 0).sum())
print("Wounded = 0:", (df['Wounded'] == 0).sum())

Killed = 0: 82925
Wounded = 0: 97182

In [28]:
df[['latitude', 'longitude']].describe()

            latitude      longitude
count  165744.000000  165744.000000
mean       23.399774      26.350909
std        18.844885      58.570068
min       -53.154613    -176.176447
25%        11.263580       2.396199
50%        31.472680      43.130000
75%        34.744167      68.451297
max        74.633553     179.366667

In [29]:
df.isnull().mean() * 100

Unnamed: 0     0.000000
Year           0.000000
Month          0.000000
Day            0.000000
Country        0.000000
Region         0.000000
city           0.000000
latitude       2.703845
longitude      2.703845
AttackType     0.000000
Killed         5.683593
Wounded        8.996184
Target         0.000000
Summary        0.000000
Group          0.000000
Target_type    0.000000
Weapon_type    0.000000
Motive         0.000000
dtype: float64

In [30]:
df.duplicated().sum()

np.int64(0)

In [34]:
df['AttackType'].value_counts()

AttackType
Bombing/Explosion                      83073
Armed Assault                          40223
Assassination                          18402
Hostage Taking (Kidnapping)            10233
Facility/Infrastructure Attack          9581
Unknown                                 6425
Unarmed Assault                          913
Hostage Taking (Barricade Incident)      902
Hijacking                                598
Name: count, dtype: int64

In [35]:
df['Target_type'].value_counts()

Target_type
Private Citizens & Property       39994
Military                          25508
Police                            22938
Government (General)              20314
Business                          19873
Transportation                     6657
Utilities                          5848
Unknown                            4873
Religious Figures/Institutions     4198
Educational Institution            4160
Government (Diplomatic)            3424
Terrorists/Non-State Militia       2859
Journalists & Media                2806
Violent Political Party            1717
Airports & Aircraft                1332
Telecommunication                   982
NGO                                 912
Other                               621
Tourists                            429
Maritime                            338
Food or Water Supply                304
Abortion Related                    263
Name: count, dtype: int64

In [36]:
df['Weapon_type'].value_counts()

Weapon_type
Explosives/Bombs/Dynamite                                                      86704
Firearms                                                                       55273
Unknown                                                                        13852
Incendiary                                                                     10459
Melee                                                                           3338
Chemical                                                                         293
Sabotage Equipment                                                               130
Vehicle (not to include vehicle-borne explosives, i.e., car or truck bombs)      116
Other                                                                            104
Biological                                                                        35
Fake Weapons                                                                      33
Radiological                                                                      13
Name: count, dtype: int64

In [32]:
print("Missing Weapon_type:", df['Weapon_type'].isnull().sum())

Missing Weapon_type: 0

In [33]:
df['Weapon_type'].value_counts(normalize=True) * 100

Weapon_type
Explosives/Bombs/Dynamite                                                      50.897564
Firearms                                                                       32.446727
Unknown                                                                         8.131494
Incendiary                                                                      6.139712
Melee                                                                           1.959495
Chemical                                                                        0.171999
Sabotage Equipment                                                              0.076313
Vehicle (not to include vehicle-borne explosives, i.e., car or truck bombs)     0.068095
Other                                                                           0.061051
Biological                                                                      0.020546
Fake Weapons                                                                    0.019372
Radiological                                                                    0.007631
Name: proportion, dtype: float64

In [37]:
df.to_csv(
    r"C:\Users\Karandeep Singh\Desktop\Tops Excel Class\Power Bi\cleaned_terrorism_data.csv",
    index=False
)

In [38]:
import os

print(os.path.abspath("cleaned_terrorism_data.csv"))

C:\Users\Karandeep Singh\Documents\New faculty classes (vikass sir MWF12pm)\cleaned_terrorism_data.csv

In [4]:
df = pd.read_csv("cleaned_terrorism_data.csv")

In [5]:
df.dtypes

Year             int64
Month            int64
Day              int64
Country            str
Region             str
city               str
latitude       float64
longitude      float64
AttackType         str
Killed         float64
Wounded        float64
Target             str
Summary            str
Group              str
Target_type        str
Weapon_type        str
Motive             str
dtype: object